canonical/charmed-kubeflow-workflows

.github/workflows/build_and_scan_rock.yaml

Wroking directory is incorrectly set in workflow. Needs to be removed.
Summary of changes:
- Removed working directory from sending scan step of workflow. Not needed.

fix: remove working directory from workflow

---

.github/workflows/build_and_publish_rock.yaml

Remove `workflow_dispatch` since there is no use for it in this repo.
On top of that, it contained a `secrets` field which would return an 
"Unexpected value 'secrets'" since this is not an allowed field.

fix(build_and_publish_rock): Remove workflow_dispatch

---

.github/workflows/get-rocks-modified.yaml

Fix workflow to run on `push` events

fix(rocks): Add checkout to get-rocks-modified.yaml

---

.github/workflows/build-scan-test-publish-rock.yaml

Trigger `publish-rock` job only on `push` events.

fix(rocks): publish rock only on push events

---

.github/workflows/integration-test-rock.yaml

Save space during integration-test-rock.yaml since this can fail when having to do with large images. See issue for details
Example run https://github.com/canonical/seldonio-rocks/actions/runs/7460461633/job/20299668263?pr=66#step:9:20
Closes https://github.com/canonical/charmed-kubeflow-workflows/issues/39

integration-test-rock.yaml: Implement save space steps

---

.github/workflows/build-rock.yaml
.github/workflows/build-scan-test-publish-rock.yaml
.github/workflows/get-rocks-modified-and-build-scan-test-publish.yaml
templates/on-pull-request-rocks-template.yaml
templates/on-push-rock-template.yaml

Add rockcraft-channel option as an option for the ROCKs CI workflows. We need this in order to use newly introduced features from rockcraft, otherwise it will by default pull from `stable`.
Ref #36

build-rock: Add rockcraft-channel option

---

.github/workflows/build-rock.yaml
.github/workflows/integration-test-rock.yaml
.github/workflows/scan-rock.yaml

ci: Decrease root-reserve-mb to fit the new runner storage
addresses https://github.com/canonical/bundle-kubeflow/issues/813

ci: Decrease root-reserve-mb to fit the new runner storage

---

.github/workflows/scan-rock.yaml

This PR increases the Trivy timemout for scanning images from default 5 mins to 50 mins. This change is needed as some ROCKs (e.g. pytorch-cpu in this [PR](https://github.com/canonical/kubeflow-rocks/pull/79)) takes time to scan (The bigger GPU ones will take even longer). This change was tested in this [PR run](https://github.com/canonical/kubeflow-rocks/actions/runs/8356385436/job/22874673810)

Increase trivy timeout

---

.github/workflows/build-rock.yaml
.github/workflows/build_and_scan_rock.yaml
.github/workflows/integration-test-rock.yaml
.github/workflows/publish-rock.yaml
.github/workflows/sanity-test-rock.yaml
.github/workflows/scan-rock.yaml

Closes: https://github.com/canonical/charmed-kubeflow-workflows/issues/53
Use rockcraft's skopeo to move the image to the Docker. More technical information is in the issue.
Test run can  be found here: https://github.com/canonical/kserve-rocks/actions/runs/9481728740/job/26166315258?pr=83

Fix skopeo in ubuntu-22.04 runner

---

.github/workflows/_publish.yaml

Use charmcraft from latest/candidate in upload-charm in order to unify the channel used during integration tests and publishing.
Ref canonical/bundle-kubeflow#993

ci(upload-charm): use charmcraft from latest/candidate

---

.github/workflows/terraform-checks.yaml

Since `apply` job may fail due to some charms having dependency, this PR makes it optional. Right now, our Terraform CI and tests story is immature. In the future, we will probably move away from those workflows, since the Terraform Charming WG is going to provide us with the required workflows, while also the testing story will be more defined.
Fixes #63

feat: Add option in TF checks to skip apply

---

.github/workflows/report-vulnerability-in-gh.yaml

This re-usable workflow can be used for reporting security vulnerabilities via Github issues. It takes the issue title, image-name, and issue-labels as inputs, and in turn:
* edits an existing issue with the same title and updates the vulnerability report
* creates a new issue with the issue-title and adds the vulnerability report in the description
Please NOTE this workflow assumes the existence of vulnerability reports as artefacts of a workflow run; that is, it expects artefacts named trivy-report-<image-name> to be present in the sabe workflow run.
Part of #69
This workflow has been tested in [this fork](https://github.com/DnPlas/kubeflow-rocks). The re-usable workflow is capable of generating [these](https://github.com/DnPlas/kubeflow-rocks/issues) type of issues. Please note how …

ci: add workflow to enable automatic vulnerability reports

---

.github/workflows/_bundle.yaml
.github/workflows/_integration-tests.yaml
.github/workflows/_observability.yaml
.github/workflows/_publish.yaml
.github/workflows/_quality-checks.yaml
.github/workflows/_unit-tests.yaml
.github/workflows/build-rock.yaml
.github/workflows/build_and_scan_rock.yaml
.github/workflows/contributing_update_all.yaml
.github/workflows/get-image-names-from-rockcraft.yaml
.github/workflows/get-published-images-scan-and-report.yaml
.github/workflows/get-rocks-modified.yaml
.github/workflows/integration-test-rock.yaml
.github/workflows/publish-rock.yaml
.github/workflows/report-vulnerability-in-gh.yaml
.github/workflows/sanity-test-rock.yaml
.github/workflows/scan-from-dockerhub-report-issue.yaml
.github/workflows/scan-from-published-image.yaml
.github/workflows/scan-rock.yaml
.github/workflows/terraform-apply.yaml
.github/workflows/terraform-checks.yaml

This PR brings all the changes from `KF-6331-dev-branch` into `main`.
* ci: add re-usable workflow for scans from published img and automatic… (https://github.com/canonical/charmed-kubeflow-workflows/pull/73)
This commit adds get-published-images-scan-and-report.yaml, a re-usable workflow
that enables repositories to scan images from a public registry (in the case
of the Analytics team it defaults to charmedkubeflow) and reports back
the security vulnerabilities as Github issues.
This workflow is intended to be used on demand (using a workflow dispatch)
and on schedule, as it will be used for continuous testing of the published
images a rock repository generates.
* ci: add workflow to enable automatic vulnerability reports (https://github.com/canonical/charmed-kubeflow-workflows/pull/72) …

feat: report vulnerabilities as GH issues and scan images from registry 

---

.github/workflows/scan-rock.yaml

This commit mitigates aquasecurity/trivy-action#389, by passing ecr registries to the TRIVY_DB_REPOSITORY and TRIVY_JAVA_DB_REPOSITORY to avoid hitting request limits.

fix: add a workaround for TOOMANYREQUESTS issue with trivy scanner

---

.github/workflows/get-image-names-from-rockcraft.yaml

The actual behaviour of the rock repositories is to check for changes in the directory where a rockcraft.yaml file lives; for any changes detected, the container image will be published. The get-image-names-from-rockcraft.yaml should also follow that pattern for correctly generating the tags of the container images that will eventually be scanned.
Manually test the bash code in a multi-rock and single-rock repos and confirm the generated image tags are correct. For example:
```bash
ubuntu@charm-dev-jammy:~/kubeflow-rocks$ pwd
/home/ubuntu/kubeflow-rocks
ubuntu@charm-dev-jammy:~/kubeflow-rocks$ git branch
* main
IMAGES_NAMES=()
paths=$(find ./ -name "rockcraft.yaml")
for d in $paths
do
short_hash=$(git log -n 1 --pretty=%h -- $(dirname ${d}))
image_name=$(yq -r '.name' ${d}) …
```

refactor: use latest change from directory for generating image tag

---

.github/workflows/_publish.yaml
.github/workflows/terraform-apply.yaml

* Bump juju to 3.6/stable
* For uniformity, use charmcraft from 3.x/stable
Ref canonical/bundle-kubeflow#1176

chore: bump juju to 3.6 + charmcraft to 3.x/stable

---

.github/workflows/get_charms_build_with_cache.yaml

This will bring a fix for the runner requesting a password when adding the runner user to the LXD group.
Fixes #89
https://github.com/canonical/kfp-operators/pull/640 is an example of how this is fixed.

ci: bump build_charm.yaml 21.0.0 -> 24.0.5

---

.github/workflows/terraform-apply.yaml

Check for unit's status instead of application in order to work around juju/juju#18625
Closes #92
* See issue for a bit of more details on the issue.
* See linked PRs that confirm run the workflow from this branch.

fix(ci): Check unit's status in terraform apply workflow

---

.github/workflows/_quality-checks.yaml

This PR temporarily changes the channel of charmcraft used in check-libs action to `latest/candidate`, by default it uses latest/stable which currently does not support platforms syntax. It is needed to work on the charmcraft.yaml `ST124` changes, for example https://github.com/canonical/kubeflow-tensorboards-operator/issues/154.

chore: use charmcraft latest/candidate for check libs

---

.github/workflows/_quality-checks.yaml

Closes #96 
Reverts the changes done in #95 now that charmcraft 3.3 is [released to stable](https://snapcraft.io/charmcraft)

Remove charmcraft pin in quality checks workflow

---

default.json

Adds a `customManager` to renovate config `default.json` to update the `pip` version in `charmcraft.yaml` files, similary to how it's done in [data-platform repos](https://github.com/canonical/data-platform/blob/main/renovate_presets/charm.json5#L120-L127).
This is now needed due to the changes in `charmcarft.yaml` in our multi-charm repos, these changes pin the pip version for reproducible builds, for example in https://github.com/canonical/kubeflow-tensorboards-operator/pull/158.
Tested on https://github.com/canonical/test-kubeflow-automation by:
1. pinning the renovate config to this branch in [renovate.json](https://github.com/canonical/test-kubeflow-automation/blob/renovate-charmcraft.yaml-build-tools/renovate.json#L4)
2. commiting a charmcraft.yaml with outdated pip version, …

chore: add renovate config for pip version in charmcraft.yaml

---

default.json

Adds a `customManager` to renovate config `default.json` to update the rust version in `charmcraft.yaml` files, similary to how it's done in [data-platform repos](https://github.com/canonical/data-platform/blob/main/renovate_presets/charm.json5#L166-L174).
This is now needed due to the changes in `charmcarft.yaml` in our multi-charm repos, these changes pin the rust version for reproducible builds, for example in https://github.com/canonical/knative-operators/pull/282.
Tested on https://github.com/canonical/test-kubeflow-automation by:
1. pinning the renovate config to this branch in [renovate.json](https://github.com/canonical/test-kubeflow-automation/blob/renovate-charmcraft.yaml-build-tools/renovate.json#L4)
2. commiting a charmcraft.yaml with outdated rust version, snippet:
```
rustup …
```

chore: add renovate config for rust version in charmcraft.yaml

---

.github/workflows/build-rock.yaml

Closes https://github.com/canonical/kubeflow-rocks/issues/205#issue-2955805898
This issue makes the `rockcraft-channel` input not required in the `build-rock` action. This makes sense because a default value is already provided (in this case "latest/stable")

fix: Make `rockcraft-channel` not required in build-rock action

---

.github/workflows/integration-test-rock.yaml

Closes #108 
Because the `https://bootstrap.pypa.io/get-pip.py` script no longer works with Python `3.8`, this PR updates the `integration-test-rock.yaml` file to use the `setup-python` action.

fix(ci): Fix integration-test-rock.yaml to use setup-python action

---

.github/workflows/build-rock.yaml
.github/workflows/build-scan-test-publish-rock.yaml
.github/workflows/integrate-rock.yaml
.github/workflows/publish-rock.yaml
.github/workflows/resolve-image-tag.yaml

Closes: https://github.com/canonical/charmed-kubeflow-workflows/issues/111
This PR introduces a new GitHub Actions workflow (`integrate-rock.yaml`) to enable automatic ROCK image integration into charm repositories using the **[CHACI](https://github.com/canonical/charmed-analytics-ci)** tool. The integration is triggered both on pull requests and after merges, streamlining the update of charm metadata with the correct image tag.
---
- **`integrate-rock.yaml`**:
- A new reusable workflow that uses `chaci integrate-rock` to update charm metadata based on the built ROCK image.
- Supports both `workflow_dispatch` (manual) and `workflow_call` (automated) triggers.
- Detects PR vs merge context and adjusts target branch and dry-run behavior accordingly.
- GPG signing is configured via …

feat: add rocks integration ci steps
